packages:
  - "apps/*"
  - "packages/*"
overrides:
  fast-jwt: ^6.3.2
  sharp: ^0.35.0
  postcss: ^8.5.12
  'minimatch@>=10>brace-expansion': ^5.0.9
  nanoid: ^3.3.18
  ajv>fast-uri: ^3.1.5
allowBuilds:
  '@google/genai': true
  '@prisma/client': true
  '@prisma/engines': true
  ffmpeg-static: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  youtube-dl-exec: true
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.10.8'
  - '@turbo/darwin-arm64@2.10.8'
  - '@turbo/linux-64@2.10.8'
  - '@turbo/linux-arm64@2.10.8'
  - '@turbo/windows-64@2.10.8'
  - '@turbo/windows-arm64@2.10.8'
  - turbo@2.10.8
