export type CaptionPreset = {
  id: string;
  name: string;
  fontFamily: string;
  fontSize: number;
  fontWeight: number;
  textColor: string;
  activeWordColor: string;
  spokenWordColor: string;
  strokeColor: string;
  strokeWidth: number;
  backgroundColor?: string;
  textTransform: "none" | "uppercase" | "lowercase";
  fontStyle?: "normal" | "italic";
  animation: "none" | "pop" | "grow" | "bounce" | "karaoke" | "shake" | "zoom-in" | "spin" | "swing" | "pulse" | "underline" | "glow" | "boxHighlight" | "typewriter" | "wordFocus";
  wordsPerCaption: number;
  maxLines: number;
  position: "top" | "center" | "bottom";
  marginBottom: number;
  enabled: boolean;
  subtitleOffset?: number; // User configurable
  isLocked?: boolean;
};

export const CAPTION_PRESETS: CaptionPreset[] = [
  {
    id: "kasisolusi",
    name: "Dr. Tirta / Shorts",
    fontFamily: "Montserrat",
    fontSize: 68,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#FFE600",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 8,
    textTransform: "uppercase",
    animation: "pop",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "word-focus",
    name: "Word Focus",
    fontFamily: "Montserrat",
    fontSize: 60,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#FFFF00",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "pop",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "temp-0",
    name: "Temp-0",
    fontFamily: "Montserrat",
    fontSize: 60,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#00FF66",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "pop",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "smart-bg-focus",
    name: "Smart BG Focus",
    fontFamily: "Inter",
    fontSize: 55,
    fontWeight: 800,
    textColor: "#FFFFFF",
    activeWordColor: "#000000",
    spokenWordColor: "#FFFFFF",
    strokeColor: "transparent",
    strokeWidth: 0,
    backgroundColor: "#FFFF00",
    textTransform: "uppercase",
    animation: "pop",
    wordsPerCaption: 3,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "box-highlight",
    name: "Box Highlight",
    fontFamily: "Montserrat",
    fontSize: 50,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#00FF00",
    spokenWordColor: "#FFFFFF",
    strokeColor: "transparent",
    strokeWidth: 0,
    backgroundColor: "rgba(0,0,0,0.75)",
    textTransform: "uppercase",
    animation: "none",
    wordsPerCaption: 3,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "underline-focus",
    name: "Underline Focus",
    fontFamily: "Inter",
    fontSize: 55,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#FF00FF",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 5,
    textTransform: "uppercase",
    animation: "grow",
    wordsPerCaption: 3,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "temp-7",
    name: "Classic (Temp-7)",
    fontFamily: "Arial",
    fontSize: 45,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#FFFF00",
    spokenWordColor: "#DDDDDD",
    strokeColor: "#000000",
    strokeWidth: 4,
    textTransform: "none",
    animation: "none",
    wordsPerCaption: 4,
    maxLines: 2,
    position: "bottom",
    marginBottom: 140,
    enabled: true
  },
  // ---- temp-1..17 (minus temp-0, temp-7 already exist) ----
  {
    id: "temp-1",
    name: "Word Focus Kuning",
    fontFamily: "Poppins",
    fontSize: 64,
    fontWeight: 800,
    textColor: "#FFFFFF",
    activeWordColor: "#FFE234",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "wordFocus",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "temp-2",
    name: "Box Highlight Ungu",
    fontFamily: "Montserrat",
    fontSize: 60,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#FFFFFF",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 4,
    backgroundColor: "#7C5CFF",
    textTransform: "uppercase",
    animation: "boxHighlight",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "temp-3",
    name: "Underline Neon Green",
    fontFamily: "Poppins",
    fontSize: 62,
    fontWeight: 800,
    textColor: "#FFFFFF",
    activeWordColor: "#3DFF97",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 5,
    textTransform: "uppercase",
    animation: "underline",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "temp-4",
    name: "Glow Magenta",
    fontFamily: "Inter",
    fontSize: 64,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#E879F9",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "glow",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "temp-5",
    name: "Pop Scale Cyan",
    fontFamily: "Montserrat",
    fontSize: 64,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#22D3EE",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "pop",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "temp-6",
    name: "Karaoke Fill Yellow",
    fontFamily: "Poppins",
    fontSize: 64,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#FFE234",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "karaoke",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "temp-8",
    name: "Red Word Focus",
    fontFamily: "Inter",
    fontSize: 60,
    fontWeight: 800,
    textColor: "#FFFFFF",
    activeWordColor: "#FF4444",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 5,
    textTransform: "uppercase",
    animation: "wordFocus",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "temp-9",
    name: "Blue Box Highlight",
    fontFamily: "Montserrat",
    fontSize: 58,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#FFFFFF",
    spokenWordColor: "#FFFFFF",
    strokeColor: "transparent",
    strokeWidth: 0,
    backgroundColor: "#3B82F6",
    textTransform: "uppercase",
    animation: "boxHighlight",
    wordsPerCaption: 3,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "temp-10",
    name: "Orange Grow",
    fontFamily: "Poppins",
    fontSize: 68,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#FF8C00",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "grow",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "temp-11",
    name: "Cyan Underline",
    fontFamily: "Poppins",
    fontSize: 60,
    fontWeight: 800,
    textColor: "#FFFFFF",
    activeWordColor: "#22D3EE",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 5,
    textTransform: "uppercase",
    animation: "underline",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "temp-12",
    name: "Green Karaoke",
    fontFamily: "Montserrat",
    fontSize: 62,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#22C55E",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 5,
    textTransform: "uppercase",
    animation: "karaoke",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "temp-13",
    name: "Blue Glow",
    fontFamily: "Inter",
    fontSize: 64,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#60A5FA",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "glow",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "temp-14",
    name: "Purple Typewriter",
    fontFamily: "Inter",
    fontSize: 60,
    fontWeight: 800,
    textColor: "#FFFFFF",
    activeWordColor: "#A78BFA",
    spokenWordColor: "#9CA3AF",
    strokeColor: "#000000",
    strokeWidth: 5,
    textTransform: "uppercase",
    animation: "typewriter",
    wordsPerCaption: 6,
    maxLines: 3,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "temp-15",
    name: "Orange Pop",
    fontFamily: "Montserrat",
    fontSize: 66,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#F97316",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "pop",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "temp-16",
    name: "Green Bounce",
    fontFamily: "Poppins",
    fontSize: 64,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#4ADE80",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "bounce",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "temp-17",
    name: "Dark Blue Box",
    fontFamily: "Montserrat",
    fontSize: 56,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#93C5FD",
    spokenWordColor: "#FFFFFF",
    strokeColor: "transparent",
    strokeWidth: 0,
    backgroundColor: "#1E3A5F",
    textTransform: "uppercase",
    animation: "boxHighlight",
    wordsPerCaption: 3,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  // ---- temp-static-1..6 ----
  {
    id: "temp-static-1",
    name: "Static White Impact",
    fontFamily: "Impact",
    fontSize: 60,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#FFFFFF",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "none",
    wordsPerCaption: 4,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "temp-static-2",
    name: "Static Clean White",
    fontFamily: "Inter",
    fontSize: 52,
    fontWeight: 700,
    textColor: "#FFFFFF",
    activeWordColor: "#FFFFFF",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 4,
    textTransform: "none",
    animation: "none",
    wordsPerCaption: 4,
    maxLines: 2,
    position: "bottom",
    marginBottom: 160,
    enabled: true
  },
  {
    id: "temp-static-3",
    name: "Static Gold Text",
    fontFamily: "Georgia",
    fontSize: 58,
    fontWeight: 700,
    textColor: "#FFD700",
    activeWordColor: "#FFD700",
    spokenWordColor: "#FFD700",
    strokeColor: "#000000",
    strokeWidth: 4,
    textTransform: "none",
    animation: "none",
    wordsPerCaption: 4,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "temp-static-4",
    name: "Static Blue Underline",
    fontFamily: "Inter",
    fontSize: 55,
    fontWeight: 700,
    textColor: "#FFFFFF",
    activeWordColor: "#60A5FA",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 4,
    textTransform: "none",
    animation: "underline",
    wordsPerCaption: 4,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "temp-static-5",
    name: "Static Center Dark BG",
    fontFamily: "Inter",
    fontSize: 48,
    fontWeight: 800,
    textColor: "#FFFFFF",
    activeWordColor: "#FFFFFF",
    spokenWordColor: "#FFFFFF",
    strokeColor: "transparent",
    strokeWidth: 0,
    backgroundColor: "rgba(0,0,0,0.7)",
    textTransform: "none",
    animation: "none",
    wordsPerCaption: 4,
    maxLines: 3,
    position: "center",
    marginBottom: 0,
    enabled: true
  },
  {
    id: "temp-static-6",
    name: "Static Top Small",
    fontFamily: "Arial",
    fontSize: 40,
    fontWeight: 700,
    textColor: "#FFFFFF",
    activeWordColor: "#FFFFFF",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 3,
    textTransform: "none",
    animation: "none",
    wordsPerCaption: 5,
    maxLines: 2,
    position: "top",
    marginBottom: 60,
    enabled: true
  },
  // ---- game-streamer-1..25 ----
  {
    id: "game-streamer-1",
    name: "Streamer Cyan Pop",
    fontFamily: "Montserrat",
    fontSize: 64,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#22D3EE",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "pop",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "game-streamer-2",
    name: "Streamer Orange Box",
    fontFamily: "Montserrat",
    fontSize: 58,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#000000",
    spokenWordColor: "#FFFFFF",
    strokeColor: "transparent",
    strokeWidth: 0,
    backgroundColor: "#F97316",
    textTransform: "uppercase",
    animation: "boxHighlight",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "game-streamer-3",
    name: "Streamer Purple Glow",
    fontFamily: "Poppins",
    fontSize: 66,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#C084FC",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "glow",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "game-streamer-4",
    name: "Streamer Green Bounce",
    fontFamily: "Montserrat",
    fontSize: 64,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#4ADE80",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "bounce",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "game-streamer-5",
    name: "Streamer Red Karaoke",
    fontFamily: "Inter",
    fontSize: 62,
    fontWeight: 800,
    textColor: "#FFFFFF",
    activeWordColor: "#FF4444",
    spokenWordColor: "#CCCCCC",
    strokeColor: "#000000",
    strokeWidth: 5,
    textTransform: "uppercase",
    animation: "karaoke",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "game-streamer-6",
    name: "Streamer Yellow Underline",
    fontFamily: "Poppins",
    fontSize: 64,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#FBBF24",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "underline",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "game-streamer-7",
    name: "Streamer Pink Pop",
    fontFamily: "Montserrat",
    fontSize: 64,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#F472B6",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "pop",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "game-streamer-8",
    name: "Streamer Top Left Word",
    fontFamily: "Inter",
    fontSize: 50,
    fontWeight: 800,
    textColor: "#FFFFFF",
    activeWordColor: "#22D3EE",
    spokenWordColor: "#9CA3AF",
    strokeColor: "#000000",
    strokeWidth: 4,
    textTransform: "uppercase",
    animation: "wordFocus",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "top",
    marginBottom: 80,
    enabled: true
  },
  {
    id: "game-streamer-9",
    name: "Streamer Top Right Box",
    fontFamily: "Montserrat",
    fontSize: 48,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#FFFFFF",
    spokenWordColor: "#FFFFFF",
    strokeColor: "transparent",
    strokeWidth: 0,
    backgroundColor: "#7C3AED",
    textTransform: "uppercase",
    animation: "boxHighlight",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "top",
    marginBottom: 80,
    enabled: true
  },
  {
    id: "game-streamer-10",
    name: "Streamer Neon Cyan Grow",
    fontFamily: "Poppins",
    fontSize: 68,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#06FFD2",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 7,
    textTransform: "uppercase",
    animation: "grow",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "game-streamer-11",
    name: "Streamer Red Yellow Pop",
    fontFamily: "Montserrat",
    fontSize: 66,
    fontWeight: 900,
    textColor: "#FFDD00",
    activeWordColor: "#FF3333",
    spokenWordColor: "#FFDD00",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "pop",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "game-streamer-12",
    name: "Streamer Purple Pink Glow",
    fontFamily: "Inter",
    fontSize: 64,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#D946EF",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "glow",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "game-streamer-13",
    name: "Streamer Dark Green Box",
    fontFamily: "Montserrat",
    fontSize: 56,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#4ADE80",
    spokenWordColor: "#FFFFFF",
    strokeColor: "transparent",
    strokeWidth: 0,
    backgroundColor: "#064E3B",
    textTransform: "uppercase",
    animation: "boxHighlight",
    wordsPerCaption: 3,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "game-streamer-14",
    name: "Streamer White Bold",
    fontFamily: "Impact",
    fontSize: 70,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#FFFFFF",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 8,
    textTransform: "uppercase",
    animation: "none",
    wordsPerCaption: 3,
    maxLines: 2,
    position: "bottom",
    marginBottom: 180,
    enabled: true
  },
  {
    id: "game-streamer-15",
    name: "Streamer Orange Black Box",
    fontFamily: "Montserrat",
    fontSize: 60,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#F97316",
    spokenWordColor: "#FFFFFF",
    strokeColor: "transparent",
    strokeWidth: 0,
    backgroundColor: "rgba(0,0,0,0.8)",
    textTransform: "uppercase",
    animation: "none",
    wordsPerCaption: 3,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "game-streamer-16",
    name: "Streamer Cyan Typewriter",
    fontFamily: "Inter",
    fontSize: 58,
    fontWeight: 800,
    textColor: "#FFFFFF",
    activeWordColor: "#22D3EE",
    spokenWordColor: "#9CA3AF",
    strokeColor: "#000000",
    strokeWidth: 5,
    textTransform: "uppercase",
    animation: "typewriter",
    wordsPerCaption: 6,
    maxLines: 3,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "game-streamer-17",
    name: "Streamer Top Center Neon",
    fontFamily: "Poppins",
    fontSize: 52,
    fontWeight: 800,
    textColor: "#FFFFFF",
    activeWordColor: "#FDE047",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 5,
    textTransform: "uppercase",
    animation: "wordFocus",
    wordsPerCaption: 3,
    maxLines: 2,
    position: "center",
    marginBottom: 0,
    enabled: true
  },
  {
    id: "game-streamer-18",
    name: "Streamer Red Underline",
    fontFamily: "Inter",
    fontSize: 60,
    fontWeight: 800,
    textColor: "#FFFFFF",
    activeWordColor: "#FF4444",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 5,
    textTransform: "uppercase",
    animation: "underline",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "game-streamer-19",
    name: "Streamer Gold Bounce",
    fontFamily: "Poppins",
    fontSize: 66,
    fontWeight: 900,
    textColor: "#FFD700",
    activeWordColor: "#FFFFFF",
    spokenWordColor: "#FFD700",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "bounce",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "game-streamer-20",
    name: "Streamer Dark Red Box",
    fontFamily: "Montserrat",
    fontSize: 54,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#FCA5A5",
    spokenWordColor: "#FFFFFF",
    strokeColor: "transparent",
    strokeWidth: 0,
    backgroundColor: "#7F1D1D",
    textTransform: "uppercase",
    animation: "boxHighlight",
    wordsPerCaption: 3,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "game-streamer-21",
    name: "Streamer Green Yellow Karaoke",
    fontFamily: "Montserrat",
    fontSize: 62,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#A3E635",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 5,
    textTransform: "uppercase",
    animation: "karaoke",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "game-streamer-22",
    name: "Streamer White Shadow",
    fontFamily: "Inter",
    fontSize: 60,
    fontWeight: 700,
    textColor: "#FFFFFF",
    activeWordColor: "#FFFFFF",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 4,
    textTransform: "none",
    animation: "none",
    wordsPerCaption: 4,
    maxLines: 2,
    position: "bottom",
    marginBottom: 160,
    enabled: true
  },
  {
    id: "game-streamer-23",
    name: "Streamer Cyan Orange Pop",
    fontFamily: "Montserrat",
    fontSize: 64,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#FB923C",
    spokenWordColor: "#22D3EE",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "pop",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "game-streamer-24",
    name: "Streamer Purple Grow",
    fontFamily: "Poppins",
    fontSize: 66,
    fontWeight: 900,
    textColor: "#FFFFFF",
    activeWordColor: "#A78BFA",
    spokenWordColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 6,
    textTransform: "uppercase",
    animation: "grow",
    wordsPerCaption: 2,
    maxLines: 2,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  },
  {
    id: "game-streamer-25",
    name: "Streamer Red Gold Typewriter",
    fontFamily: "Inter",
    fontSize: 58,
    fontWeight: 800,
    textColor: "#FFD700",
    activeWordColor: "#FF4444",
    spokenWordColor: "#FFD700",
    strokeColor: "#000000",
    strokeWidth: 5,
    textTransform: "uppercase",
    animation: "typewriter",
    wordsPerCaption: 6,
    maxLines: 3,
    position: "bottom",
    marginBottom: 200,
    enabled: true
  }
];

export function getPresetById(id: string): CaptionPreset {
  return CAPTION_PRESETS.find(p => p.id === id) || CAPTION_PRESETS[0];
}

export function getDefaultPreset(): CaptionPreset {
  return CAPTION_PRESETS[0];
}
